### ISSUE TITLE
export 'ReactP5Wrapper' (imported as 'ReactP5Wrapper') was not found in 'react-p5-wrapper' (module has no exports)

### ISSUE THREAD

**Issue by syntax-co** [jamesrweb/react-p5-wrapper#219]
## Expected Behavior
expected no errors

## Actual Behavior
export 'ReactP5Wrapper' (imported as 'ReactP5Wrapper') was not found in 'react-p5-wrapper' (module has no exports)

## Steps to Reproduce the Problem

1. I was following the instructions on npm to get started with the wrapper;
2. I imported the component 

   `import { ReactP5Wrapper } from "react-p5-wrapper";`

## Specifications

Package Version: 4.0.1

**Comment by jamesrweb** [comment]
Are you sure everything is installed correctly? I tested everything last night when I released the [v4.0.1](https://github.com/P5-wrapper/react/discussions/218) patch fix and again just now with a fresh project and everything renders and animates as expected in the docs (see images below).

<img width="712" alt="Bildschirmfoto 2023-01-23 um 01 10 56" src="https://user-images.githubusercontent.com/47126579/213947971-beaba23b-8b85-4ce8-832d-a059aef84da5.png">
<img width="526" alt="Bildschirmfoto 2023-01-23 um 01 11 00" src="https://user-images.githubusercontent.com/47126579/213947975-b5fb18bb-a2c9-43ec-8260-af0a5a50dd20.png">
<img width="664" alt="Bildschirmfoto 2023-01-23 um 01 10 52" src="https://user-images.githubusercontent.com/47126579/213947970-ec7add6d-b458-44a3-b695-ac4e4cc33af2.png">
<img width="320" alt="Bildschirmfoto 2023-01-23 um 01 12 13" src="https://user-images.githubusercontent.com/47126579/213947993-dc359132-3dfa-42d1-a139-2b1cb97c2583.png">

**Comment by jamesrweb** [comment]
If you updated an existing project, try removing `node_modules` and `package-lock.json` (assuming you are using npm and not pnpm (pnpm-lock.yaml) or yarn (yarn.lock)) and then reinstalling the dependencies because perhaps its just some NPM cache is broken... That's the only thing I can think of.

**Comment by dimadem** [comment]
Hi, I have the same issue at this point, I've done with reinstall all packages, but issue is not solved.

**Comment by syntax-co** [comment]
The problem has actually resolved itself, there seems to be no direct reasoning for this because everything was spelled exactly the same way. I wish I could offer a reason behind it.

**Comment by jamesrweb** [comment]
> Hi, I have the same issue at this point, I've done with reinstall all packages, but issue is not solved.

What package manager are you using?

What steps did you take to install the package?

What have you tried already?

Is there a specific message or log you can share?

**Comment by jamesrweb** [comment]
> The problem has actually resolved itself, there seems to be no direct reasoning for this because everything was spelled exactly the same way. I wish I could offer a reason behind it.
> 
>  

I'm almost 100% sure it's a local cache somewhere. Probably in the global mode cache or with the local project lock file / node_modules.

**Comment by syntax-co** [comment]
I am using npm, I had followed the instructions from the docs to install it using " npm install react-p5-wrapper". I have tried deleting the node module folder and the package-lock.json and it still comes up the same results on other projects. I have tried clearing the cache as well

**Comment by syntax-co** [comment]
It appears that package 3.4.0 works fine and does not bring up the error but once I install ^4.0.0 it starts giving errors

**Comment by jamesrweb** [comment]
> Are you sure everything is installed correctly? I tested everything last night when I released the [v4.0.1](https://github.com/P5-wrapper/react/discussions/218) patch fix and again just now with a fresh project and everything renders and animates as expected in the docs (see images below).
> 
> 
> 
> <img width="712" alt="Bildschirmfoto 2023-01-23 um 01 10 56" src="https://user-images.githubusercontent.com/47126579/213947971-beaba23b-8b85-4ce8-832d-a059aef84da5.png">
> 
> <img width="526" alt="Bildschirmfoto 2023-01-23 um 01 11 00" src="https://user-images.githubusercontent.com/47126579/213947975-b5fb18bb-a2c9-43ec-8260-af0a5a50dd20.png">
> 
> <img width="664" alt="Bildschirmfoto 2023-01-23 um 01 10 52" src="https://user-images.githubusercontent.com/47126579/213947970-ec7add6d-b458-44a3-b695-ac4e4cc33af2.png">
> 
> <img width="320" alt="Bildschirmfoto 2023-01-23 um 01 12 13" src="https://user-images.githubusercontent.com/47126579/213947993-dc359132-3dfa-42d1-a139-2b1cb97c2583.png">
> 
> 

As mentioned here and in the release notes you need 4.0.1 since it patches 4.0.0. No one should be using 4.0.0.

**Comment by jamesrweb** [comment]
@syntax-co are you able to share any further details about your setup / code? I am curious why this is happening for you since I cannot reproduce the issue. @dimadem has his issue due to nextjs limitations and maybe #223 could help but it still has issues that nextjs sadly introduces as described in #222. Either way, if you are not using nextjs then I would like to know more to try and support because I see no issue on my end with a fresh install or upgrading existing projects 🙍🏻‍♂️.

**Comment by jamesrweb** [comment]
@syntax-co and @dimadem please try upgrading to [version 4.1.0](https://github.com/P5-wrapper/react/releases/tag/v4.1.0) and see if that helps you at all.

If not then @dimadem the answer given in #222 still stands and @syntax-co I will need to above requested information.

If it does resolve the issue though then let me know and I can close this issue accordingly 😄.

**Comment by dimadem** [comment]
> @syntax-co and @dimadem please try upgrading to [version 4.1.0](https://github.com/P5-wrapper/react/releases/tag/v4.1.0) and see if that helps you at all.
> 
> If not then @dimadem the answer given in #222 still stands and @syntax-co I will need to above requested information.
> 
> If it does resolve the issue though then let me know and I can close this issue accordingly 😄.

I've update to new version, and it's working, thank you

**Comment by jamesrweb** [comment]
@syntax-co I will close this issue since it seems the issue is resolved but if this is still an issue, please comment below and I will reopen the issue again.
